# Generated by Django 2.2.3 on 2019-07-14 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('TC', models.IntegerField(primary_key=True, serialize=False)),
                ('PersonelAd', models.CharField(max_length=255)),
                ('PersonelSoyad', models.CharField(max_length=255)),
                ('DogumTarihi', models.DateField()),
                ('TelefonNumarasi', models.CharField(max_length=20)),
                ('Unvan', models.CharField(max_length=50)),
                ('BaslamaTarihi', models.DateField()),
            ],
            options={
                'db_table': 'Personel',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sube',
            fields=[
                ('SubeID', models.IntegerField(primary_key=True, serialize=False)),
                ('SubeAdi', models.CharField(max_length=255)),
                ('SubeYer', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Sube',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Yonetici',
            fields=[
                ('YoneticiID', models.IntegerField(primary_key=True, serialize=False)),
                ('TC', models.ForeignKey(db_column='TC', on_delete=django.db.models.deletion.DO_NOTHING, to='ControlSite.Personel')),
            ],
            options={
                'db_table': 'Yonetici',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='YillikIzin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CikisTarihi', models.DateField()),
                ('GirisTarihi', models.DateField()),
                ('YillikIzin', models.IntegerField()),
                ('OnayID', models.ForeignKey(db_column='YoneticiID', on_delete=django.db.models.deletion.DO_NOTHING, to='ControlSite.Yonetici')),
                ('TC', models.ForeignKey(db_column='TC', on_delete=django.db.models.deletion.DO_NOTHING, to='ControlSite.Personel')),
            ],
            options={
                'db_table': 'YillikIzin',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SistemTablosu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GirisSaati', models.DateTimeField()),
                ('CikisSaati', models.DateTimeField()),
                ('TC', models.ForeignKey(db_column='TC', on_delete=django.db.models.deletion.DO_NOTHING, to='ControlSite.Personel')),
            ],
            options={
                'db_table': 'SistemTablosu',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='personel',
            name='SubeID',
            field=models.ForeignKey(db_column='SubeID', on_delete=django.db.models.deletion.DO_NOTHING, to='ControlSite.Sube'),
        ),
        migrations.CreateModel(
            name='Mazeret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gerekce', models.CharField(max_length=255)),
                ('Baslama', models.DateField()),
                ('Bitis', models.DateField()),
                ('OnayID', models.ForeignKey(db_column='YoneticiID', on_delete=django.db.models.deletion.DO_NOTHING, to='ControlSite.Yonetici')),
                ('TC', models.ForeignKey(db_column='TC', on_delete=django.db.models.deletion.DO_NOTHING, to='ControlSite.Personel')),
            ],
            options={
                'db_table': 'Mazeret',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FazlaMesai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Baslama', models.DateField()),
                ('Bitis', models.DateField()),
                ('Aciklama', models.CharField(max_length=255)),
                ('SubeID', models.ForeignKey(db_column='SubeID', on_delete=django.db.models.deletion.DO_NOTHING, to='ControlSite.Sube')),
                ('TC', models.ForeignKey(db_column='TC', on_delete=django.db.models.deletion.DO_NOTHING, to='ControlSite.Personel')),
            ],
            options={
                'db_table': 'FazlaMesai',
                'managed': True,
            },
        ),
    ]
